version: "3.9"
services:
  gitactions:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gitactions
    env_file: .env
    ports: 
      - "3000:3000"
    volumes: 
      - .:/usr/src/app
    tty: true
